language: node_js

node_js:
    - "12"
    - "13"
    - "14"
    - "16"
    - "18"

env:
    - NODE_ENV=test

install:
    - npm install
    - npm install express sass
    - npm run build

cache: npm
